// チャットエリアの横幅を統一
export const CHAT_AREA_WIDTH = "80vw";

export const chatDemo = [
  {
    key: 2134141,
    sendID: "xxxx",
    text: "yFxavYjMCCWtsFcYIcamoUfnevVBgviGyBzRBhfVMdaCPdiIFBKQkMMgozLwMtMhfyOCpycuXgFBgZRhGiuXPuVEkiViinfTnLwp",
    time: "09:00",
    read: true,
  },
  {
    key: 2134142,
    sendID: "yyyy",
    text: "yFxavYjMCCWtsFcYIcamoUfnevVBgviGy",
    time: "09:00",
    read: true,
  },
  {
    key: 2134143,
    sendID: "yyyy",
    text: "yFxavYjMCCWtsFcYIcamoUfnevVBgviGyBzRBhfVMdaCPdiIFBKQ",
    time: "09:00",
    read: true,
  },
  {
    key: 2134144,
    sendID: "xxxx",
    text: "yFxavYjMCCWtsFcYIcamoUfnkiViinfTnLwp",
    time: "09:00",
    read: true,
  },
  {
    key: 2134145,
    sendID: "yyyy",
    text: "yFxavYjMCCWtsFcYIcamMdaCPdiIFBKBgZRhGiuXPuVEkiViinfTnLwp",
    time: "09:00",
    read: true,
  },
  {
    key: 2134146,
    sendID: "yyyy",
    text: "yFxavYjMCCWtsFcYIcamoUfnevVBgviGyBzRBhfVMdaCPdiIFBhfyOCpycuXgFBgZRhGiuXPuVEkiViinfTnLwp",
    time: "09:00",
    read: true,
  },
  {
    key: 2134144,
    sendID: "xxxx",
    text: "yFxavYjMCCWtsFcYIcamoUfnkiViinfTnLwp",
    time: "09:00",
    read: true,
  },
  {
    key: 2134145,
    sendID: "yyyy",
    text: "yFxavYjMCCWtsFcYIcamMdaCPdiIFBKBgZRhGiuXPuVEkiViinfTnLwp",
    time: "09:00",
    read: true,
  },
  {
    key: 2134146,
    sendID: "yyyy",
    text: "yFxavYjMCCWtsFcYIcamoUfnevVBgviGyBzRBhfVMdaCPdiIFBhfyOCpycuXgFBgZRhGiuXPuVEkiViinfTnLwp",
    time: "09:00",
    read: true,
  },
  {
    key: 2134144,
    sendID: "xxxx",
    text: "yFxavYjMCCWtsFcYIcamoUfnkiViinfTnLwp",
    time: "09:00",
    read: true,
  },
  {
    key: 2134145,
    sendID: "yyyy",
    text: "yFxavYjMCCWtsFcYIcamMdaCPdiIFBKBgZRhGiuXPuVEkiViinfTnLwp",
    time: "09:00",
    read: true,
  },
  {
    key: 2134146,
    sendID: "yyyy",
    text: "yFxavYjMCCWtsFcYIcamoUfnevVBgviGyBzRBhfVMdaCPdiIFBhfyOCpycuXgFBgZRhGiuXPuVEkiViinfTnLwp",
    time: "09:00",
    read: true,
  },
  {
    key: 2134144,
    sendID: "xxxx",
    text: "yFxavYjMCCWtsFcYIcamoUfnkiViinfTnLwp",
    time: "09:00",
    read: true,
  },
  {
    key: 2134145,
    sendID: "yyyy",
    text: "yFxavYjMCCWtsFcYIcamMdaCPdiIFBKBgZRhGiuXPuVEkiViinfTnLwp",
    time: "09:00",
    read: true,
  },
  {
    key: 2134146,
    sendID: "yyyy",
    text: "yFxavYjMCCWtsFcYIcamoUfnevVBgviGyBzRBhfVMdaCPdiIFBhfyOCpycuXgFBgZRhGiuXPuVEkiViinfTnLwp",
    time: "09:00",
    read: true,
  },
  {
    key: 2134144,
    sendID: "xxxx",
    text: "yFxavYjMCCWtsFcYIcamoUfnkiViinfTnLwp",
    time: "09:00",
    read: true,
  },
  {
    key: 2134145,
    sendID: "yyyy",
    text: "yFxavYjMCCWtsFcYIcamMdaCPdiIFBKBgZRhGiuXPuVEkiViinfTnLwp",
    time: "09:00",
    read: true,
  },
  {
    key: 2134146,
    sendID: "yyyy",
    text: "yFxavYjMCCWtsFcYIcamoUfnevVBgviGyBzRBhfVMdaCPdiIFBhfyOCpycuXgFBgZRhGiuXPuVEkiViinfTnLwp",
    time: "09:00",
    read: true,
  },
  {
    key: 2134144,
    sendID: "xxxx",
    text: "yFxavYjMCCWtsFcYIcamoUfnkiViinfTnLwp",
    time: "09:00",
    read: true,
  },
  {
    key: 2134145,
    sendID: "yyyy",
    text: "yFxavYjMCCWtsFcYIcamMdaCPdiIFBKBgZRhGiuXPuVEkiViinfTnLwp",
    time: "09:00",
    read: true,
  },
  {
    key: 2134146,
    sendID: "yyyy",
    text: "yFxavYjMCCWtsFcYIcamoUfnevVBgviGyBzRBhfVMdaCPdiIFBhfyOCpycuXgFBgZRhGiuXPuVEkiViinfTnLwp",
    time: "09:00",
    read: true,
  },
  {
    key: 2134147,
    sendID: "xxxx",
    text: "OK",
    time: "09:00",
    read: true,
  },
];
